mod_group_id=fr.samlegamer.mcwterraformersmc
maven_group=fr.samlegamer.mcwterraformersmc

mod_id=mcwterraformersmc
archives_base_name=mcwterraformersmc
mod_name=Macaw's TerraformersMC

mod_license=All Rights Reserved
mod_authors=Samlegamer
mod_description=This mod is a multi-compatibility for the mods developed by the TerraformersMC Team. Like Traverse, Cinderscapes or Terrestria.

mod_issue_tracker=https://github.com/Samlegamer/Macaw-s-Addons/issues
mod_project_url=https://www.curseforge.com/minecraft/mc-mods/macaws-terraformersmc

mod_init=fr.samlegamer.mcwterraformersmc.McwTerraformersMC
mod_init_client=fr.samlegamer.mcwterraformersmc.Client
mod_init_datagen=fr.samlegamer.mcwterraformersmc.Data
