modLoader="javafml"
loaderVersion="[44,)"

license="${mod_license}"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Addons/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-biomes-o-plenty"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="biomesoplenty"
mandatory=true
versionRange="NONE"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="addonslib"
mandatory=true
versionRange="[1.19.3-1.5,)"
ordering="BEFORE"
side="BOTH"