mod_group_id=fr.samlegamer.mcwaurora

mod_id=mcwaurora
mod_name=Macaw's Aurora

mod_license=All Rights Reserved
mod_authors=Samlegamer
mod_description=A compatibility for Macaw's Bridges/Fences/Roofs/Furnitures to Aurora Team mod Enhanced Mushrooms.

website_link=https://www.curseforge.com/minecraft/mc-mods/macaws-aurora
issues_link=https://github.com/Samlegamer/Macaw-s-Addons/issues
