modLoader="javafml"
loaderVersion="[40,)"

license="${mod_license}"
issueTrackerURL="https://github.com/Samlegamer/Macaw-s-Addons/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://curseforge.com/minecraft/mc-mods/macaws-quark"
logoFile="logo.png"
credits="sketch_macaw"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="quark"
mandatory=true
versionRange="NONE"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="autoreglib"
mandatory=true
versionRange="NONE"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="addonslib"
mandatory=true
versionRange="[1.18.2-1.5,)"
ordering="BEFORE"
side="BOTH"
