package fr.samlegamer.mcwbyg;

import fr.samlegamer.addonslib.data.ModType;
import fr.samlegamer.addonslib.generation.recipes.McwRecipes;
import fr.samlegamer.addonslib.generation.recipes.mat.McwStoneMat;
import fr.samlegamer.addonslib.generation.recipes.mat.McwWoodMat;
import net.fabricmc.fabric.api.datagen.v1.FabricDataGenerator;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider;
import net.minecraft.block.Block;
import net.minecraft.data.server.recipe.RecipeJsonProvider;
import potionstudios.byg.BYG;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;

import static potionstudios.byg.common.block.BYGBlocks.*;
import static potionstudios.byg.common.block.BYGBlocks.ARAUCARIA_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.ASPEN_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.ASPEN_LOG;
import static potionstudios.byg.common.block.BYGBlocks.ASPEN_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.ASPEN_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.ASPEN_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.BAOBAB_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.BAOBAB_LOG;
import static potionstudios.byg.common.block.BYGBlocks.BAOBAB_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.BAOBAB_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.BAOBAB_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.BLOOMING_WITCH_HAZEL_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.BLUE_ENCHANTED_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.BLUE_ENCHANTED_LOG;
import static potionstudios.byg.common.block.BYGBlocks.BLUE_ENCHANTED_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.BLUE_ENCHANTED_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.BLUE_ENCHANTED_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.BLUE_SPRUCE_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.BROWN_BIRCH_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.BROWN_OAK_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.BULBIS_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.BULBIS_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.BULBIS_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.BULBIS_STEM;
import static potionstudios.byg.common.block.BYGBlocks.BULBIS_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.CHERRY_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.CHERRY_LOG;
import static potionstudios.byg.common.block.BYGBlocks.CHERRY_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.CHERRY_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.CHERRY_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.CIKA_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.CIKA_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.CIKA_LOG;
import static potionstudios.byg.common.block.BYGBlocks.CIKA_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.CIKA_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.CIKA_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.CRYPTIC_STONE;
import static potionstudios.byg.common.block.BYGBlocks.CRYPTIC_STONE_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.CRYPTIC_STONE_WALL;
import static potionstudios.byg.common.block.BYGBlocks.CYPRESS_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.CYPRESS_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.CYPRESS_LOG;
import static potionstudios.byg.common.block.BYGBlocks.CYPRESS_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.CYPRESS_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.CYPRESS_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.DACITE;
import static potionstudios.byg.common.block.BYGBlocks.DACITE_BRICKS;
import static potionstudios.byg.common.block.BYGBlocks.DACITE_BRICK_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.DACITE_BRICK_WALL;
import static potionstudios.byg.common.block.BYGBlocks.DACITE_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.DACITE_WALL;
import static potionstudios.byg.common.block.BYGBlocks.EBONY_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.EBONY_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.EBONY_LOG;
import static potionstudios.byg.common.block.BYGBlocks.EBONY_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.EBONY_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.EBONY_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.ETHER_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.ETHER_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.ETHER_LOG;
import static potionstudios.byg.common.block.BYGBlocks.ETHER_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.ETHER_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.ETHER_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.FIR_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.FIR_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.FIR_LOG;
import static potionstudios.byg.common.block.BYGBlocks.FIR_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.FIR_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.FIR_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.FLOWERING_INDIGO_JACARANDA_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.FLOWERING_JACARANDA_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.FLOWERING_ORCHARD_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.FLOWERING_PALO_VERDE_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.FUNGAL_IMPARIUS_STEM;
import static potionstudios.byg.common.block.BYGBlocks.GREEN_ENCHANTED_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.GREEN_ENCHANTED_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.GREEN_ENCHANTED_LOG;
import static potionstudios.byg.common.block.BYGBlocks.GREEN_ENCHANTED_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.GREEN_ENCHANTED_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.GREEN_ENCHANTED_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.HOLLY_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.HOLLY_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.HOLLY_LOG;
import static potionstudios.byg.common.block.BYGBlocks.HOLLY_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.HOLLY_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.HOLLY_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.IMPARIUS_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.IMPARIUS_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.IMPARIUS_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.IMPARIUS_STEM;
import static potionstudios.byg.common.block.BYGBlocks.IMPARIUS_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.JACARANDA_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.JACARANDA_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.JACARANDA_LOG;
import static potionstudios.byg.common.block.BYGBlocks.JACARANDA_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.JACARANDA_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.JACARANDA_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.LAMENT_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.LAMENT_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.LAMENT_LOG;
import static potionstudios.byg.common.block.BYGBlocks.LAMENT_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.LAMENT_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.LAMENT_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.MAHOGANY_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.MAHOGANY_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.MAHOGANY_LOG;
import static potionstudios.byg.common.block.BYGBlocks.MAHOGANY_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.MAHOGANY_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.MAHOGANY_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.MANGROVE_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.MANGROVE_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.MANGROVE_LOG;
import static potionstudios.byg.common.block.BYGBlocks.MANGROVE_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.MANGROVE_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.MANGROVE_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.MAPLE_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.MAPLE_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.MAPLE_LOG;
import static potionstudios.byg.common.block.BYGBlocks.MAPLE_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.MAPLE_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.MAPLE_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.NIGHTSHADE_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.NIGHTSHADE_LOG;
import static potionstudios.byg.common.block.BYGBlocks.NIGHTSHADE_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.NIGHTSHADE_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.NIGHTSHADE_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.ORANGE_BIRCH_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.ORANGE_OAK_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.ORANGE_SPRUCE_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.PALM_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.PALM_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.PALM_LOG;
import static potionstudios.byg.common.block.BYGBlocks.PALM_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.PALM_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.PALM_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.PALO_VERDE_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.PINE_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.PINE_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.PINE_LOG;
import static potionstudios.byg.common.block.BYGBlocks.PINE_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.PINE_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.PINE_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.PINK_CHERRY_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.POLISHED_SOAPSTONE;
import static potionstudios.byg.common.block.BYGBlocks.POLISHED_TRAVERTINE;
import static potionstudios.byg.common.block.BYGBlocks.POLISHED_TRAVERTINE_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.POLISHED_TRAVERTINE_WALL;
import static potionstudios.byg.common.block.BYGBlocks.PURPUR_STONE;
import static potionstudios.byg.common.block.BYGBlocks.PURPUR_STONE_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.PURPUR_STONE_WALL;
import static potionstudios.byg.common.block.BYGBlocks.RAINBOW_EUCALYPTUS_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.RAINBOW_EUCALYPTUS_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.RAINBOW_EUCALYPTUS_LOG;
import static potionstudios.byg.common.block.BYGBlocks.RAINBOW_EUCALYPTUS_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.RAINBOW_EUCALYPTUS_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.RAINBOW_EUCALYPTUS_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.REDWOOD_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.REDWOOD_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.REDWOOD_LOG;
import static potionstudios.byg.common.block.BYGBlocks.REDWOOD_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.REDWOOD_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.REDWOOD_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.RED_BIRCH_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.RED_OAK_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.RED_ROCK;
import static potionstudios.byg.common.block.BYGBlocks.RED_ROCK_BRICKS;
import static potionstudios.byg.common.block.BYGBlocks.RED_ROCK_BRICK_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.RED_ROCK_BRICK_WALL;
import static potionstudios.byg.common.block.BYGBlocks.RED_ROCK_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.RED_ROCK_WALL;
import static potionstudios.byg.common.block.BYGBlocks.RED_SPRUCE_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.SCORIA_STONE;
import static potionstudios.byg.common.block.BYGBlocks.SCORIA_STONEBRICKS;
import static potionstudios.byg.common.block.BYGBlocks.SCORIA_STONEBRICK_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.SCORIA_STONEBRICK_WALL;
import static potionstudios.byg.common.block.BYGBlocks.SKYRIS_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.SKYRIS_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.SKYRIS_LOG;
import static potionstudios.byg.common.block.BYGBlocks.SKYRIS_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.SKYRIS_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.SKYRIS_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.SOAPSTONE;
import static potionstudios.byg.common.block.BYGBlocks.SOAPSTONE_BRICKS;
import static potionstudios.byg.common.block.BYGBlocks.SOAPSTONE_BRICK_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.SOAPSTONE_BRICK_WALL;
import static potionstudios.byg.common.block.BYGBlocks.SOAPSTONE_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.SOAPSTONE_WALL;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_ASPEN_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_BAOBAB_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_BLUE_ENCHANTED_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_BULBIS_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_CHERRY_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_CIKA_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_CYPRESS_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_EBONY_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_ETHER_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_FIR_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_GREEN_ENCHANTED_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_HOLLY_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_JACARANDA_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_LAMENT_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_MAHOGANY_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_MANGROVE_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_MAPLE_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_NIGHTSHADE_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_PALM_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_PINE_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_RAINBOW_EUCALYPTUS_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_REDWOOD_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_SKYRIS_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_SYTHIAN_STEM;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_WILLOW_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_WITCH_HAZEL_LOG;
import static potionstudios.byg.common.block.BYGBlocks.STRIPPED_ZELKOVA_LOG;
import static potionstudios.byg.common.block.BYGBlocks.SYTHIAN_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.SYTHIAN_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.SYTHIAN_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.SYTHIAN_STEM;
import static potionstudios.byg.common.block.BYGBlocks.SYTHIAN_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.TRAVERTINE;
import static potionstudios.byg.common.block.BYGBlocks.TRAVERTINE_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.TRAVERTINE_WALL;
import static potionstudios.byg.common.block.BYGBlocks.WHITE_CHERRY_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.WILLOW_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.WILLOW_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.WILLOW_LOG;
import static potionstudios.byg.common.block.BYGBlocks.WILLOW_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.WILLOW_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.WILLOW_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.WITCH_HAZEL_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.WITCH_HAZEL_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.WITCH_HAZEL_LOG;
import static potionstudios.byg.common.block.BYGBlocks.WITCH_HAZEL_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.WITCH_HAZEL_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.WITCH_HAZEL_TRAPDOOR;
import static potionstudios.byg.common.block.BYGBlocks.YELLOW_BIRCH_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.YELLOW_SPRUCE_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.ZELKOVA_FENCE;
import static potionstudios.byg.common.block.BYGBlocks.ZELKOVA_LEAVES;
import static potionstudios.byg.common.block.BYGBlocks.ZELKOVA_LOG;
import static potionstudios.byg.common.block.BYGBlocks.ZELKOVA_PLANKS;
import static potionstudios.byg.common.block.BYGBlocks.ZELKOVA_SLAB;
import static potionstudios.byg.common.block.BYGBlocks.ZELKOVA_TRAPDOOR;

public class Recipes extends FabricRecipeProvider
{
    public Recipes(FabricDataGenerator dataGenerator) {
        super(dataGenerator);
    }

    @Override
    protected void generateRecipes(Consumer<RecipeJsonProvider> consumer) {
        McwRecipes.registerAllMcwWood(consumer, McwByg.MODID, BYG.MOD_ID, McwByg.WOOD, getWood());
        McwRecipes.registerMcwHedge(consumer, McwByg.MODID, BYG.MOD_ID, McwByg.LEAVES, getLeaves());
        McwRecipes.onRegisterMcwStone(ModType.BRIDGES, consumer, McwByg.MODID, BYG.MOD_ID, McwByg.bridges_rockable, getStoneBridges());
        McwRecipes.onRegisterMcwStone(ModType.FENCES, consumer, McwByg.MODID, BYG.MOD_ID, McwByg.fences_rockable, getStoneFencesAndRoofs());
        McwRecipes.onRegisterMcwStone(ModType.ROOFS, consumer, McwByg.MODID, BYG.MOD_ID, McwByg.fences_rockable, getStoneFencesAndRoofs());
    }

    private static List<Block> getLeaves()
    {
        List<Block> mats = new ArrayList<>();
        mats.add(ASPEN_LEAVES.get());
        mats.add(BAOBAB_LEAVES.get());
        mats.add(BLUE_ENCHANTED_LEAVES.get());
        mats.add(CIKA_LEAVES.get());
        mats.add(CYPRESS_LEAVES.get());
        mats.add(EBONY_LEAVES.get());
        mats.add(ETHER_LEAVES.get());
        mats.add(FIR_LEAVES.get());
        mats.add(GREEN_ENCHANTED_LEAVES.get());
        mats.add(HOLLY_LEAVES.get());
        mats.add(JACARANDA_LEAVES.get());
        mats.add(LAMENT_LEAVES.get());
        mats.add(MAHOGANY_LEAVES.get());
        mats.add(MAPLE_LEAVES.get());
        mats.add(PALM_LEAVES.get());
        mats.add(PINE_LEAVES.get());
        mats.add(RAINBOW_EUCALYPTUS_LEAVES.get());
        mats.add(REDWOOD_LEAVES.get());
        mats.add(SKYRIS_LEAVES.get());
        mats.add(MANGROVE_LEAVES.get());
        mats.add(WILLOW_LEAVES.get());
        mats.add(WITCH_HAZEL_LEAVES.get());
        mats.add(ZELKOVA_LEAVES.get());
        mats.add(BLUE_SPRUCE_LEAVES.get());
        mats.add(ORANGE_SPRUCE_LEAVES.get());
        mats.add(RED_SPRUCE_LEAVES.get());
        mats.add(YELLOW_SPRUCE_LEAVES.get());
        mats.add(BROWN_BIRCH_LEAVES.get());
        mats.add(ORANGE_BIRCH_LEAVES.get());
        mats.add(RED_BIRCH_LEAVES.get());
        mats.add(YELLOW_BIRCH_LEAVES.get());
        mats.add(BROWN_OAK_LEAVES.get());
        mats.add(ORANGE_OAK_LEAVES.get());
        mats.add(RED_OAK_LEAVES.get());
        mats.add(WHITE_CHERRY_LEAVES.get());
        mats.add(PINK_CHERRY_LEAVES.get());
        mats.add(ARAUCARIA_LEAVES.get());
        mats.add(BLOOMING_WITCH_HAZEL_LEAVES.get());
        mats.add(FLOWERING_INDIGO_JACARANDA_LEAVES.get());
        mats.add(FLOWERING_JACARANDA_LEAVES.get());
        mats.add(FLOWERING_ORCHARD_LEAVES.get());
        mats.add(FLOWERING_PALO_VERDE_LEAVES.get());
        mats.add(PALO_VERDE_LEAVES.get());
        return mats;
    }

    private static List<McwStoneMat> getStoneBridges()
    {
        List<McwStoneMat> mats = new ArrayList<>();
        mats.add(new McwStoneMat(CRYPTIC_STONE.get(), CRYPTIC_STONE_WALL.get(), CRYPTIC_STONE_SLAB.get(), CRYPTIC_STONE.get()));
        mats.add(new McwStoneMat(DACITE_BRICKS.get(), DACITE_BRICK_WALL.get(), DACITE_BRICK_SLAB.get(), DACITE.get()));
        mats.add(new McwStoneMat(POLISHED_TRAVERTINE.get(), POLISHED_TRAVERTINE_WALL.get(), POLISHED_TRAVERTINE_SLAB.get(), TRAVERTINE.get()));
        mats.add(new McwStoneMat(PURPUR_STONE.get(), PURPUR_STONE_WALL.get(), PURPUR_STONE_SLAB.get(), PURPUR_STONE.get()));
        mats.add(new McwStoneMat(RED_ROCK_BRICKS.get(), RED_ROCK_BRICK_WALL.get(), RED_ROCK_BRICK_SLAB.get(), RED_ROCK_BRICKS.get()));
        mats.add(new McwStoneMat(SCORIA_STONEBRICKS.get(), SCORIA_STONEBRICK_WALL.get(), SCORIA_STONEBRICK_SLAB.get(), SCORIA_STONEBRICKS.get()));
        mats.add(new McwStoneMat(SOAPSTONE_BRICKS.get(), SOAPSTONE_BRICK_WALL.get(), SOAPSTONE_BRICK_SLAB.get(), SOAPSTONE_BRICKS.get()));
        return mats;
    }

    private static List<McwStoneMat> getStoneFencesAndRoofs()
    {
        List<McwStoneMat> mats = new ArrayList<>();
        mats.add(new McwStoneMat(SOAPSTONE.get(), SOAPSTONE_WALL.get(), SOAPSTONE_SLAB.get(), POLISHED_SOAPSTONE.get()));
        mats.add(new McwStoneMat(TRAVERTINE.get(), TRAVERTINE_WALL.get(), TRAVERTINE_SLAB.get(), POLISHED_TRAVERTINE.get()));
        mats.add(new McwStoneMat(DACITE.get(), DACITE_WALL.get(), DACITE_SLAB.get(), DACITE_BRICKS.get()));
        mats.add(new McwStoneMat(RED_ROCK.get(), RED_ROCK_WALL.get(), RED_ROCK_SLAB.get(), RED_ROCK_BRICKS.get()));
        mats.add(new McwStoneMat(SCORIA_STONE.get(), SCORIA_STONEBRICK_WALL.get(), SCORIA_STONEBRICK_SLAB.get(), SCORIA_STONEBRICKS.get()));        return mats;
    }

    private static List<McwWoodMat> getWood()
    {
        List<McwWoodMat> mats = new ArrayList<>();
        mats.add(new McwWoodMat(ASPEN_LOG.get(), ASPEN_PLANKS.get(), STRIPPED_ASPEN_LOG.get(), ASPEN_SLAB.get(), ASPEN_FENCE.get(), ASPEN_TRAPDOOR.get()));
        mats.add(new McwWoodMat(BAOBAB_LOG.get(), BAOBAB_PLANKS.get(), STRIPPED_BAOBAB_LOG.get(), BAOBAB_SLAB.get(), BAOBAB_FENCE.get(), BAOBAB_TRAPDOOR.get()));
        mats.add(new McwWoodMat(BLUE_ENCHANTED_LOG.get(), BLUE_ENCHANTED_PLANKS.get(), STRIPPED_BLUE_ENCHANTED_LOG.get(), BLUE_ENCHANTED_SLAB.get(), BLUE_ENCHANTED_FENCE.get(), BLUE_ENCHANTED_TRAPDOOR.get()));
        mats.add(new McwWoodMat(CHERRY_LOG.get(), CHERRY_PLANKS.get(), STRIPPED_CHERRY_LOG.get(), CHERRY_SLAB.get(), CHERRY_FENCE.get(), CHERRY_TRAPDOOR.get()));
        mats.add(new McwWoodMat(CIKA_LOG.get(), CIKA_PLANKS.get(), STRIPPED_CIKA_LOG.get(), CIKA_SLAB.get(), CIKA_FENCE.get(), CIKA_TRAPDOOR.get()));
        mats.add(new McwWoodMat(CYPRESS_LOG.get(), CYPRESS_PLANKS.get(), STRIPPED_CYPRESS_LOG.get(), CYPRESS_SLAB.get(), CYPRESS_FENCE.get(), CYPRESS_TRAPDOOR.get()));
        mats.add(new McwWoodMat(EBONY_LOG.get(), EBONY_PLANKS.get(), STRIPPED_EBONY_LOG.get(), EBONY_SLAB.get(), EBONY_FENCE.get(), EBONY_TRAPDOOR.get()));
        mats.add(new McwWoodMat(ETHER_LOG.get(), ETHER_PLANKS.get(), STRIPPED_ETHER_LOG.get(), ETHER_SLAB.get(), ETHER_FENCE.get(), ETHER_TRAPDOOR.get()));
        mats.add(new McwWoodMat(FIR_LOG.get(), FIR_PLANKS.get(), STRIPPED_FIR_LOG.get(), FIR_SLAB.get(), FIR_FENCE.get(), FIR_TRAPDOOR.get()));
        mats.add(new McwWoodMat(GREEN_ENCHANTED_LOG.get(), GREEN_ENCHANTED_PLANKS.get(), STRIPPED_GREEN_ENCHANTED_LOG.get(), GREEN_ENCHANTED_SLAB.get(), GREEN_ENCHANTED_FENCE.get(), GREEN_ENCHANTED_TRAPDOOR.get()));
        mats.add(new McwWoodMat(HOLLY_LOG.get(), HOLLY_PLANKS.get(), STRIPPED_HOLLY_LOG.get(), HOLLY_SLAB.get(), HOLLY_FENCE.get(), HOLLY_TRAPDOOR.get()));
        mats.add(new McwWoodMat(JACARANDA_LOG.get(), JACARANDA_PLANKS.get(), STRIPPED_JACARANDA_LOG.get(), JACARANDA_SLAB.get(), JACARANDA_FENCE.get(), JACARANDA_TRAPDOOR.get()));
        mats.add(new McwWoodMat(LAMENT_LOG.get(), LAMENT_PLANKS.get(), STRIPPED_LAMENT_LOG.get(), LAMENT_SLAB.get(), LAMENT_FENCE.get(), LAMENT_TRAPDOOR.get()));
        mats.add(new McwWoodMat(MAHOGANY_LOG.get(), MAHOGANY_PLANKS.get(), STRIPPED_MAHOGANY_LOG.get(), MAHOGANY_SLAB.get(), MAHOGANY_FENCE.get(), MAHOGANY_TRAPDOOR.get()));
        mats.add(new McwWoodMat(MANGROVE_LOG.get(), MANGROVE_PLANKS.get(), STRIPPED_MANGROVE_LOG.get(), MANGROVE_SLAB.get(), MANGROVE_FENCE.get(), MANGROVE_TRAPDOOR.get()));
        mats.add(new McwWoodMat(MAPLE_LOG.get(), MAPLE_PLANKS.get(), STRIPPED_MAPLE_LOG.get(), MAPLE_SLAB.get(), MAPLE_FENCE.get(), MAPLE_TRAPDOOR.get()));
        mats.add(new McwWoodMat(NIGHTSHADE_LOG.get(), NIGHTSHADE_PLANKS.get(), STRIPPED_NIGHTSHADE_LOG.get(), NIGHTSHADE_SLAB.get(), NIGHTSHADE_FENCE.get(), NIGHTSHADE_TRAPDOOR.get()));
        mats.add(new McwWoodMat(PALM_LOG.get(), PALM_PLANKS.get(), STRIPPED_PALM_LOG.get(), PALM_SLAB.get(), PALM_FENCE.get(), PALM_TRAPDOOR.get()));
        mats.add(new McwWoodMat(PINE_LOG.get(), PINE_PLANKS.get(), STRIPPED_PINE_LOG.get(), PINE_SLAB.get(), PINE_FENCE.get(), PINE_TRAPDOOR.get()));
        mats.add(new McwWoodMat(RAINBOW_EUCALYPTUS_LOG.get(), RAINBOW_EUCALYPTUS_PLANKS.get(), STRIPPED_RAINBOW_EUCALYPTUS_LOG.get(), RAINBOW_EUCALYPTUS_SLAB.get(), RAINBOW_EUCALYPTUS_FENCE.get(), RAINBOW_EUCALYPTUS_TRAPDOOR.get()));
        mats.add(new McwWoodMat(REDWOOD_LOG.get(), REDWOOD_PLANKS.get(), STRIPPED_REDWOOD_LOG.get(), REDWOOD_SLAB.get(), REDWOOD_FENCE.get(), REDWOOD_TRAPDOOR.get()));
        mats.add(new McwWoodMat(SKYRIS_LOG.get(), SKYRIS_PLANKS.get(), STRIPPED_SKYRIS_LOG.get(), SKYRIS_SLAB.get(), SKYRIS_FENCE.get(), SKYRIS_TRAPDOOR.get()));
        mats.add(new McwWoodMat(WILLOW_LOG.get(), WILLOW_PLANKS.get(), STRIPPED_WILLOW_LOG.get(), WILLOW_SLAB.get(), WILLOW_FENCE.get(), WILLOW_TRAPDOOR.get()));
        mats.add(new McwWoodMat(WITCH_HAZEL_LOG.get(), WITCH_HAZEL_PLANKS.get(), STRIPPED_WITCH_HAZEL_LOG.get(), WITCH_HAZEL_SLAB.get(), WITCH_HAZEL_FENCE.get(), WITCH_HAZEL_TRAPDOOR.get()));
        mats.add(new McwWoodMat(ZELKOVA_LOG.get(), ZELKOVA_PLANKS.get(), STRIPPED_ZELKOVA_LOG.get(), ZELKOVA_SLAB.get(), ZELKOVA_FENCE.get(), ZELKOVA_TRAPDOOR.get()));
        mats.add(new McwWoodMat(BULBIS_STEM.get(), BULBIS_PLANKS.get(), STRIPPED_BULBIS_LOG.get(), BULBIS_SLAB.get(), BULBIS_FENCE.get(), BULBIS_TRAPDOOR.get()));
        mats.add(new McwWoodMat(IMPARIUS_STEM.get(), IMPARIUS_PLANKS.get(), FUNGAL_IMPARIUS_STEM.get(), IMPARIUS_SLAB.get(), IMPARIUS_FENCE.get(), IMPARIUS_TRAPDOOR.get()));
        mats.add(new McwWoodMat(SYTHIAN_STEM.get(), SYTHIAN_PLANKS.get(), STRIPPED_SYTHIAN_STEM.get(), SYTHIAN_SLAB.get(), SYTHIAN_FENCE.get(), SYTHIAN_TRAPDOOR.get()));
        return mats;
    }
}
