modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="${issues_link}"

[[mods]] #mandatory
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${website_link}"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description2}'''

[[dependencies.${mod_id}]] #optional
modId = "neoforge" #mandatory
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[${neoforge_version},)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.${mod_id}]]
modId = "minecraft"
type="required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="biomeswevegone"
type="required"
versionRange="NONE"
ordering="BEFORE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="addonslib"
type="required"
versionRange="[1.21.4-1.8,)"
ordering="BEFORE"
side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
